Alcohol: 50
Car Maintenance: 30
Car: 10
Clothing: 25
Education: 20
Entertainment: 100
Gas: 25
Gifts: 30
Groceries: 200
Health Insurance: 15
Household: 100
Investment: 0
Out of Pocket Medical: 250
Personal Care: 50
Personal Expenses: 20
Retirement Savings: 100
Safety Net: 1000
Subscriptions: 10
Take-Out: 50